site_name: Window Accent
site_description: Window Accent helps you distinguish between multiple JetBrains IDE windows with visual cues
site_url: https://plugins.jetbrains.com/plugin/31895-window-accent/

repo_name: View on GitHub
repo_url: https://github.com/alexBlakeGoudemond/jetbrains-window-accent

theme:
  name: material

  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow

    - content.code.copy

    - search.highlight
    - search.suggest

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md

  - Getting Started:
      - Installation: installation.md
      - Configuration: configuration.md
      - FAQ: faq.md

  - Screenshots:
      - Screenshots: screenshots.md

  - Compatibility:
      - Supported IDEs: compatibility.md
      - Verification Process: verification.md
      - Verification Reports (Success - all):
          - 2026.1.2 (v 1.0.5): compatibility-verification/gradle-verify-plugin-success-v1.0.5-2026.1.2.md
          - 2025.3.5 (v 1.0.4): compatibility-verification/gradle-verify-plugin-success-v1.0.4-2025.3.5.md
          - 2025.3.3 (v 1.0.4): compatibility-verification/compatibility-verification-success-deprecated-and-experimental-api-results-v1.0.2-2025.3.md
          - 2025.2.6.2 (v 1.0.4): compatibility-verification/gradle-verify-plugin-success-v1.0.4-2025.2.6.2.md
          - 2025.1.7.1 (v 1.0.4): compatibility-verification/gradle-verify-plugin-success-v1.0.4-2025.1.7.1.md
      - Verification Reports (Failure - 1.2.10):
          - 2026.1 (v 1.2.10): compatibility-verification/compatibility-verification-failure-analysis-v1.2.10-2026.1.md
      - Verification Reports (Failure - 1.2.5):
          - 2026.2 EAP (v 1.2.5): compatibility-verification/compatibility-verification-failure-analysis-v1.2.5-2026.2-eap.md
      - Verification Reports (Failure - 1.0.5):
          - 2024.3.7.1 (v 1.0.5): compatibility-verification/gradle-verify-plugin-failure-v1.0.5-2024.3.7.1.md

  - Development:
      - Changelog: window-accent-changelog.md
      - Contributing: contributing.md

  - Privacy: privacy.md