package com.window_accent

import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.diagnostic.logger
import java.lang.ref.WeakReference

/**
 * Development-only utility that checks whether the plugin ClassLoader can be
 * garbage-collected after plugin cleanup, and — if not — attempts to identify
 * the strong-reference path keeping it alive.
 *
 * This is a **no-op in production** (non-internal) IDE builds.
 *
 * ## ⚠️ IMPORTANT — Do NOT call from the plugin unload path
 *
 * [scheduleLeakCheck] must NOT be called from [PluginLifecycleListener.beforePluginUnload]
 * or any other plugin lifecycle hook that runs during dynamic unload.
 *
 * **Why:** IntelliJ's GC collectibility check runs shortly after `beforePluginUnload` returns.
 * Any plugin code executing on any thread at that moment — including the lambda dispatched by
 * [scheduleLeakCheck] — keeps the `PluginClassLoader` reachable, because every class loaded by
 * that classloader holds a hard reference back to it via `Class.classLoader`. The diagnostic
 * will therefore always produce a false positive, appearing as:
 *
 * ```
 * ROOT: Java Frame: ClassLoaderLeakDiagnostics$$Lambda.run(...)
 * (root): ClassLoaderLeakDiagnostics$$Lambda
 * <class>: java.lang.Class
 * * cachedConstructor: PluginClassLoader
 * ```
 *
 * This self-interference was confirmed across multiple hprof snapshots (v1.2.10 log batches 2 & 3).
 *
 * ## Intended usage
 *
 * This class is reserved for **ad-hoc investigation only**. To diagnose a suspected new leak:
 * 1. Temporarily re-add the `scheduleLeakCheck` call to `beforePluginUnload`.
 * 2. Run `./gradlew runIde` (which already sets `idea.is.internal=true` and
 *    `ide.plugins.snapshot.on.unload.fail=true`).
 * 3. Trigger a plugin disable/update.
 * 4. Examine the `LeakDiagnostics`-tagged log lines and the generated `.hprof` snapshot.
 * 5. Remove the call again before committing.
 *
 * The hprof snapshot (auto-generated by IntelliJ on genuine unload failure) is the primary
 * diagnostic tool — it does not require any plugin code to be running during the check.
 *
 * Two scanning strategies are used in sequence when a leak is detected:
 *
 * 1. **Thread-stack scan** — iterates all live [Thread] stacks looking for frames
 *    whose declaring class was loaded by the plugin ClassLoader.
 *
 * 2. **`com.intellij.testFramework.LeakHunter` scan** — invoked reflectively so that
 *    no compile-time dependency on `intellij.platform.testFramework` is required.
 *    LeakHunter walks the strong-reference graph from a known root and reports the
 *    full path to the retained object. Available in `runIde` and internal IDE builds.
 */
internal object ClassLoaderLeakDiagnostics {

    private val LOG = logger<ClassLoaderLeakDiagnostics>()

    private const val LEAK_HUNTER_CLASS = "com.intellij.testFramework.LeakHunter"

    /** Milliseconds to wait before triggering GC, giving cleanup tasks time to complete. */
    private const val WAIT_BEFORE_GC_MS = 3_000L

    /** Number of [System.gc] calls made before concluding the ClassLoader is still retained. */
    private const val GC_ROUNDS = 5

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Schedules a background check that verifies [classLoader] is eligible for GC
     * after plugin cleanup.
     *
     * Only active when [com.intellij.openapi.application.Application.isInternal] is
     * true (e.g., when running via `runIde` with `-Didea.is.internal=true`).
     *
     * @param classLoader The plugin ClassLoader to monitor — typically obtained from
     *                    [com.intellij.ide.plugins.IdeaPluginDescriptor.getPluginClassLoader].
     */
    fun scheduleLeakCheck(classLoader: ClassLoader) {
        if (!isInternalMode()) {
            LOG.debug("[Window Accent][LeakDiagnostics] Skipping leak check — not running in internal IDE mode")
            return
        }

        val weakRef = WeakReference(classLoader)
        LOG.info("[Window Accent][LeakDiagnostics] ClassLoader GC check scheduled (delay=${WAIT_BEFORE_GC_MS}ms, gcRounds=$GC_ROUNDS)")

        ApplicationManager.getApplication().executeOnPooledThread {
            // IMPORTANT: do NOT capture `classLoader` directly in this lambda.
            // The lambda object is held in the thread pool's task queue and then on the
            // pooled thread's stack frame for the entire duration of performLeakCheck.
            // A direct capture would create a strong reference to the PluginClassLoader
            // that is reachable during IntelliJ's GC collectibility check — making
            // ClassLoaderLeakDiagnostics itself the retaining root (confirmed in v1.2.10 logs).
            // Only the WeakReference is captured; the strong ref is obtained inside
            // performLeakCheck after the GC rounds, once it is safe to do so.
            try {
                performLeakCheck(weakRef)
            } catch (e: Exception) {
                LOG.warn("[Window Accent][LeakDiagnostics] Unexpected error during leak check", e)
            }
        }
    }

    // -------------------------------------------------------------------------
    // Internal implementation
    // -------------------------------------------------------------------------

    /**
     * Waits, triggers GC, then checks whether [weakRef] was cleared.
     *
     * The [ClassLoader] is intentionally NOT passed as a parameter here — see the
     * call-site comment in [scheduleLeakCheck]. A strong reference in this method's
     * frame would itself be the GC root keeping the ClassLoader alive during IntelliJ's
     * collectibility check (confirmed root cause in v1.2.10 log: `ROOT: Java Frame:
     * ClassLoaderLeakDiagnostics.performLeakCheck`).
     *
     * Instead, the strong reference is obtained from [weakRef] only after the GC rounds
     * have completed. At that point, if the reference is still non-null, the ClassLoader
     * is retained by something *other* than this frame, and we can safely hold it for
     * further scanning.
     */
    private fun performLeakCheck(weakRef: WeakReference<ClassLoader>) {
        Thread.sleep(WAIT_BEFORE_GC_MS)

        repeat(GC_ROUNDS) {
            System.gc()
            Thread.sleep(200)
        }

        // Obtain the strong reference only after GC rounds. If the ClassLoader was
        // collected, this returns null and we exit cleanly. If it is still alive, the
        // retaining root is somewhere else — safe to hold a local ref for scanning.
        val leakedClassLoader = weakRef.get()
        if (leakedClassLoader == null) {
            LOG.info("[Window Accent][LeakDiagnostics] ✓ ClassLoader was GC'd — no leak detected")
            return
        }

        LOG.warn(
            "[Window Accent][LeakDiagnostics] ✗ ClassLoader is still reachable after cleanup " +
                    "+ $GC_ROUNDS GC rounds. Running diagnostic scans..."
        )

        scanThreadStacksForPluginClasses(leakedClassLoader)
        runLeakHunterScan(leakedClassLoader)
    }

    /**
     * Checks all live thread stacks for frames whose declaring class was **loaded by**
     * [classLoader] (i.e. `Class.classLoader === classLoader`).
     *
     * The previous implementation used `Class.forName(name, false, classLoader)` which
     * succeeds for any class *accessible through* the classloader's parent-delegation
     * chain — producing ~150 false-positive platform threads (CoroutineScheduler workers,
     * Netty, ForkJoinPool, etc.). The fix is to also verify the loaded class's own
     * `classLoader` field is exactly the plugin ClassLoader, filtering to only classes
     * that genuinely originate from the plugin.
     *
     * This catches the common case where a plugin background thread (e.g., an Alarm task
     * or coroutine) is still executing, holding the ClassLoader alive.
     */
    private fun scanThreadStacksForPluginClasses(classLoader: ClassLoader) {
        val retainingThreads = Thread.getAllStackTraces().entries
            .filter { (_, frames) ->
                frames.any { frame -> isPluginClass(frame.className, classLoader) }
            }

        if (retainingThreads.isEmpty()) {
            LOG.info("[Window Accent][LeakDiagnostics] Thread-stack scan: no live threads executing plugin code")
            return
        }

        LOG.warn("[Window Accent][LeakDiagnostics] Thread-stack scan: ${retainingThreads.size} thread(s) still running plugin code:")
        retainingThreads.forEach { (thread, frames) ->
            val pluginFrames = frames.filter { frame -> isPluginClass(frame.className, classLoader) }
            LOG.warn(
                "[Window Accent][LeakDiagnostics]   Thread '${thread.name}' (state=${thread.state}) — " +
                        "plugin frames: ${pluginFrames.map { it.className + "." + it.methodName }}"
            )
        }
    }

    /**
     * Returns true only if [className] names a class that was **loaded by** [classLoader]
     * (i.e. the class's own [Class.getClassLoader] is the same instance as [classLoader]).
     *
     * Checking `Class.forName(name, false, classLoader) != null` alone is insufficient —
     * it succeeds for platform classes accessible via parent delegation, producing false
     * positives. The additional `loadedClass.classLoader === classLoader` guard ensures
     * we only report genuine plugin classes.
     */
    private fun isPluginClass(className: String, classLoader: ClassLoader): Boolean {
        return try {
            val loadedClass = Class.forName(className, false, classLoader)
            loadedClass.classLoader === classLoader
        } catch (_: ClassNotFoundException) {
            false
        } catch (_: LinkageError) {
            false
        }
    }

    /**
 * Reflectively invokes `com.intellij.testFramework.LeakHunter.checkLeak` to walk
 * the strong-reference graph and report the path from a GC root to [classLoader].
     *
     * LeakHunter is part of `intellij.platform.testFramework` and is available in the
     * IDE classpath during `runIde`. If the class is absent (e.g., in a slimmed runtime)
     * this step is silently skipped with an informational log entry.
     *
     * When LeakHunter detects a reference path it throws [AssertionError] whose message
     * contains the full path — we catch it and write it to the IDE log as a warning.
     */
    private fun runLeakHunterScan(classLoader: ClassLoader) {
        val leakHunterClass = try {
            Class.forName(LEAK_HUNTER_CLASS)
        } catch (_: ClassNotFoundException) {
            LOG.info(
                "[Window Accent][LeakDiagnostics] LeakHunter not available " +
                        "($LEAK_HUNTER_CLASS not on classpath). " +
                        "Tip: pass -Didea.is.internal=true when running via runIde to surface this scan."
            )
            return
        }

        LOG.info("[Window Accent][LeakDiagnostics] LeakHunter found — scanning for strong references to the ClassLoader...")

        // LeakHunter.checkLeak(root, suspectClass, predicate) — traverses the object
        // graph from `root` and throws AssertionError with the path when `predicate` matches.
        val checkLeakMethod = leakHunterClass.methods
            .firstOrNull { method ->
                method.name == "checkLeak"
                        && method.parameterCount == 3
                        && method.parameterTypes[1] == Class::class.java
            }

        if (checkLeakMethod == null) {
            LOG.warn("[Window Accent][LeakDiagnostics] Could not locate LeakHunter.checkLeak(root, Class, Predicate) — API may have changed")
            return
        }

        // Predicate: match the ClassLoader itself, or any object whose class was loaded
        // by it (indicating a plugin-class instance is still live).
        val predicate = java.util.function.Predicate<Any> { candidate ->
            candidate === classLoader || candidate.javaClass.classLoader === classLoader
        }

        val scanRoot = ApplicationManager.getApplication()
        try {
            checkLeakMethod.invoke(null, scanRoot, ClassLoader::class.java, predicate)
            LOG.info("[Window Accent][LeakDiagnostics] LeakHunter: no ClassLoader reference found from app root")
        } catch (e: java.lang.reflect.InvocationTargetException) {
            when (val cause = e.cause) {
                is AssertionError -> LOG.warn(
                    "[Window Accent][LeakDiagnostics] LeakHunter found a strong-reference path to the ClassLoader:\n${cause.message}"
                )
                else -> LOG.warn("[Window Accent][LeakDiagnostics] LeakHunter scan threw an unexpected error", cause ?: e)
            }
        }
    }

    private fun isInternalMode(): Boolean {
        return try {
            ApplicationManager.getApplication().isInternal
        } catch (_: Exception) {
            false
        }
    }
}





