package com.window_accent

import com.intellij.openapi.project.Project
import com.window_accent.configuration.tool_window.WindowAccentToolWindowFactory
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.nio.file.Files
import java.nio.file.Paths
import java.util.*

/**
 * The tests defined here serve as proof that feedback from the Jetbrains marketplace
 * Compatibility Verification has been acknowledged and addressed.
 *
 * Commands like `./gradlew verifyPlugin --rerun-tasks --info` will reveal Deprecated API usage etc
 * */
class CompatibilityVerificationTest {

    /**
     * Validated that the modern replacement `shouldBeAvailable(Project)` is correctly implemented.
     * This replaces `ToolWindowFactory.isApplicable()`
     * */
    @Test
    fun testShouldBeAvailableIsOverridden() {
        val methods = WindowAccentToolWindowFactory::class.java.methods
        val isOverridden = Arrays.stream(methods)
            .anyMatch { m ->
                m.name == "shouldBeAvailable" &&
                        m.parameterCount == 1 &&
                        m.parameterTypes[0] == Project::class.java
            }

        assertTrue(isOverridden, "WindowColorPanelToolWindowFactory should have shouldBeAvailable(Project)")
    }

    /**
     * VERIFIES DEPRECATED API REMOVAL:
     * AppExecutorUtil.getAppScheduledExecutorService() should NO LONGER be present.
     */
    @Test
    fun testDeprecatedAppScheduledExecutorServiceIsRemoved() {
        val sourcePath = Paths.get("src", "main", "kotlin", "com", "window_color_panel", "feature", "window_color", "WindowColorApplier.kt")
        val content = String(Files.readAllBytes(sourcePath))

        assertFalse(
            content.contains("AppExecutorUtil.getAppScheduledExecutorService()"),
            "WindowColorApplier.kt should NOT contain AppExecutorUtil.getAppScheduledExecutorService() after the fix"
        )
    }

    /**
     * Ensures through reflection that these deprecated methods are not explicitly overridden in `WindowColorPanelToolWindowFactory`.
     * We ignore synthetic/bridge methods as they are generated by the compiler for interface compatibility.
     * */
    @Test
    fun testDeprecatedMethodsAreNotOverridden() {
        val methods = WindowAccentToolWindowFactory::class.java.declaredMethods

        val isIsApplicableOverridden = Arrays.stream(methods)
            .anyMatch { m -> m.name == "isApplicable" && !m.isSynthetic && !m.isBridge }

        val isIsDoNotActivateOnStartOverridden = Arrays.stream(methods)
            .anyMatch { m -> m.name == "isDoNotActivateOnStart" && !m.isSynthetic && !m.isBridge }

        val methodDetails = methods.map { "${it.name}(synthetic=${it.isSynthetic}, bridge=${it.isBridge})" }

        assertFalse(
            isIsApplicableOverridden,
            "WindowColorPanelToolWindowFactory should not override deprecated isApplicable. Found methods: $methodDetails"
        )
        assertFalse(
            isIsDoNotActivateOnStartOverridden,
            "WindowColorPanelToolWindowFactory should not override deprecated isDoNotActivateOnStart. Found methods: $methodDetails"
        )
    }

    /**
     * Verify that `getAnchor()`, `getIcon()`, and `manage()` are not explicitly overridden
     * in `WindowColorPanelToolWindowFactory`, preventing accidental use of experimental APIs.
     * */
    @Test
    fun testExperimentalMethodsAreNotOverridden() {
        val methods = WindowAccentToolWindowFactory::class.java.declaredMethods

        val isGetAnchorOverridden = Arrays.stream(methods)
            .anyMatch { m -> m.name == "getAnchor" && !m.isSynthetic && !m.isBridge }

        val isGetIconOverridden = Arrays.stream(methods)
            .anyMatch { m -> m.name == "getIcon" && !m.isSynthetic && !m.isBridge }

        val isManageOverridden = Arrays.stream(methods)
            .anyMatch { m -> m.name == "manage" && !m.isSynthetic && !m.isBridge }

        val methodDetails = methods.map { "${it.name}(synthetic=${it.isSynthetic}, bridge=${it.isBridge})" }

        assertFalse(
            isGetAnchorOverridden,
            "WindowColorPanelToolWindowFactory should not override experimental getAnchor. Found methods: $methodDetails"
        )
        assertFalse(
            isGetIconOverridden,
            "WindowColorPanelToolWindowFactory should not override experimental getIcon. Found methods: $methodDetails"
        )
        assertFalse(
            isManageOverridden,
            "WindowColorPanelToolWindowFactory should not override experimental manage. Found methods: $methodDetails"
        )
    }

    /**
     * Validates that the plugin is configured as a dynamic plugin (no restart required).
     * This allows the plugin to be installed, updated, or uninstalled without restarting the IDE.
     * */
    @Test
    fun testPluginIsDynamic() {
        val pluginXmlPath = Paths.get("src", "main", "resources", "META-INF", "plugin.xml")
        val content = String(Files.readAllBytes(pluginXmlPath))

        assertTrue(
            content.contains("require-restart=\"false\""),
            "plugin.xml should contain require-restart=\"false\" to support dynamic loading/unloading"
        )
    }

    /**
     * Validates that the plugin only depends on the core platform module.
     * This ensures no accidental dependencies on optional or heavy modules like Git or XPath
     * are introduced, which might lead to "Unavailable" warnings in the Marketplace.
     * */
    @Test
    fun testPluginXmlDependenciesIncluded() {
        val pluginXmlPath = Paths.get("src", "main", "resources", "META-INF", "plugin.xml")
        val content = String(Files.readAllBytes(pluginXmlPath))

        assertTrue(
            content.contains("<depends>com.intellij.modules.platform</depends>"),
            "plugin.xml should contain dependency on com.intellij.modules.platform"
        )
    }

    /**
     * Validates that the plugin does not depend on inherited dependencies, for example: Git4Idea or XPathView.
     * These modules might lead to "Unavailable" warnings in the Marketplace, which is preferred over including.
     *
     * Note: Explicitly declaring inherited dependencies like Git4Idea or XPathView is discouraged
     * unless the plugin actually uses their APIs, as it limits IDE compatibility and does not
     * resolve platform-level optional dependency warnings.
     * */
    @Test
    fun testPluginXmlDependenciesExcluded() {
        val pluginXmlPath = Paths.get("src", "main", "resources", "META-INF", "plugin.xml")
        val content = String(Files.readAllBytes(pluginXmlPath))

        // Ensure no other depends tags are present that might be pulling in Git or XPath
        val dependsCount = "<depends>".toRegex().findAll(content).count()
        assertTrue(
            dependsCount == 1,
            "There should be exactly one <depends> tag, found $dependsCount. Check for accidental dependencies."
        )

        // Explicitly check for discouraged dependencies that were discussed
        assertFalse(
            content.contains("Git4Idea"),
            "Explicit dependency on Git4Idea is discouraged for this platform-only plugin."
        )
        assertFalse(
            content.contains("XPathView"),
            "Explicit dependency on XPathView is discouraged for this platform-only plugin."
        )
    }

    /**
     * Validate the presence of `anchor` and `icon` attributes in `plugin.xml`
     * */
    @Test
    fun testPluginXmlHasModernConfigurations() {
        val pluginXmlPath = Paths.get("src", "main", "resources", "META-INF", "plugin.xml")
        val content = String(Files.readAllBytes(pluginXmlPath))

        assertTrue(
            content.contains("anchor=\"left\""),
            "plugin.xml should contain anchor=\"left\" in the toolWindow extension"
        )
        assertTrue(
            content.contains("icon=\"/META-INF/simple-plugin-icon.svg\""),
            "plugin.xml should contain icon attribute in the toolWindow extension"
        )
    }

    /**
     * Validated that `doNotActivateOnStart` is correctly set in `plugin.xml`.
     * This replaces `ToolWindowFactory.isDoNotActivateOnStart()`
     * */
    @Test
    fun testPluginXmlHasDoNotActivateOnStart() {
        val pluginXmlPath = Paths.get("src", "main", "resources", "META-INF", "plugin.xml")
        val content = String(Files.readAllBytes(pluginXmlPath))

        assertTrue(
            content.contains("doNotActivateOnStart=\"true\""),
            "plugin.xml should contain doNotActivateOnStart=\"true\" in the toolWindow extension"
        )
    }

}
